$(function(){
  $('.headTitle').hover(
    function(){
      $('#title-kaicho').hide();
      $('#kanegon').fadeIn(1000);
    },
    function(){
      $('#title-kaicho').show();
      $('#kanegon').hide();
    }
  )
});
