$(function(){
  $('.titlelogo').hover(
    function(){
      $('#title-kaicho').hide();
      $('#kanegon').show();
    },
    function(){
      $('#title-kaicho').show();
      $('#kanegon').hide();
    }
  )
});
