$(function(){
  $('.titlelogo').hover(
    function(){
      $('#title-kaicho').fadeOut();
      $('#kanegon').fadeIn();
    },
    function(){
      $('#title-kaicho').show();
      $('#kanegon').hide();
    }
  )
});
